### ISSUE TITLE
confusion regarding Vec interface

### ISSUE THREAD

**Issue by rich-murphey** [ctsrc/persistence#1]
I'm confused about how to use this.  The documentation says "providing a Vec-like data structure".  However MmapedVec doesn't seem to have a Deref impl.  That's confusing, since "impl Deref for MmapedVec<T> would typically need to be defined in the MmapedVec crate.

It looks interesting and useful.  I just can't figure out how to use the crate as is.

**Comment by ctsrc** [comment]
Hi, thank you for submitting this issue and my apologies for not seeing that you had opened this issue before now.

This crate is very early work in progress at the moment, so I have not yet written the docs about how to actually use this crate, because I expect that there will be some changes to be done first before the crate is really usable to people.

**Comment by rich-murphey** [comment]
Hey, thanks for clarifying.  This does look interesting.
For one thing there's been a steady intermittent news about entity component systems in rust, but they don't have the ergonomics of something like this that provides direct access to the elements.

I'm closing this, but am still interested. Best regards.
